### PR TITLE
chore: constants fix

### LINKED ISSUE #12: chore: add units to constants
There should be units for the constants that we are using. I shouldn't have to head over to the file to see the comment to know what unit it is. For example:
```diff
- public static final double WHEEL_LOCK_TIME = 10; // seconds
+ public static final double WHEEL_LOCK_TIME_SECS = 10;
```
Also, all constants should be uppercase.
```diff
- public static final int kDriverControllerPort = 0;
+ public static final int DRIVER_CONTROLLER_PORT = 0;
```

Also consider this: https://docs.wpilib.org/en/stable/docs/software/basic-programming/java-units.html#converting-units. With this you won't have to add the units to the constants as the type already gives us the information we need.

### PR DESCRIPTION
**Pull request by JetBluefan1**
- closes #12

### CODE REVIEW

File: src/main/java/frc/robot/Constants.java [hunk 1]
```diff
@@ -18,11 +23,11 @@
  * constants are needed, to reduce verbosity.
  */
 public final class Constants {
-  public static final double ROBOT_MASS = (148 - 20.3) * 0.453592; // 32lbs * kg per pound
+  public static final double ROBOT_MASS_KG = (148 - 20.3) * 0.453592; // 32lbs * kg per pound
```
Comment (minhd-vu) [inline src/main/java/frc/robot/Constants.java]:
```suggestion
    public static final Measure<Mass> ROBOT_MASS = Pounds.of(125); 
```

We don't know the weight but we can set it to the max for now.

File: src/main/java/frc/robot/Constants.java [hunk 2]
```diff
@@ -18,11 +23,11 @@
...
   public static final Matter CHASSIS =
-      new Matter(new Translation3d(0, 0, Units.inchesToMeters(8)), ROBOT_MASS);
-  public static final double LOOP_TIME = 0.13; // s, 20ms + 110ms sprk max velocity lag
-  public static final double MAX_SPEED = Units.feetToMeters(14.5);
+      new Matter(new Translation3d(0, 0, Units.inchesToMeters(8)), ROBOT_MASS_KG);
+  public static final double LOOP_TIME_SECS = 0.13; // s, 20ms + 110ms sprk max velocity lag
```
Comment (minhd-vu) [inline src/main/java/frc/robot/Constants.java]:
```suggestion
  public static final Measure<Time> LOOP_TIME = Seconds(0.13); // s, 20ms + 110ms sprk max velocity lag
```

File: src/main/java/frc/robot/Constants.java [hunk 3]
```diff
@@ -31,11 +38,11 @@ public static final class AutoConstants {
 
   public static final class DrivebaseConstants {
     // Hold time on motor brakes when disabled.
-    public static final double WHEEL_LOCK_TIME = 10; // seconds
+    public static final double WHEEL_LOCK_TIME_SECS = 10; // seconds
```
Comment (minhd-vu) [inline src/main/java/frc/robot/Constants.java]: fix this to use the Measure<Time> above

File: src/main/java/frc/robot/commands/drivebase/AbsoluteFieldDrive.java [hunk 4]
```diff
@@ -64,8 +67,8 @@ public void execute() {
             translation,
             swerve.getFieldVelocity(),
             swerve.getPose(),
-            Constants.LOOP_TIME,
-            Constants.ROBOT_MASS,
+            Constants.LOOP_TIME.in(Seconds),
+            Constants.ROBOT_MASS.in(Pounds),
```
Comment (minhd-vu) [inline src/main/java/frc/robot/commands/drivebase/AbsoluteFieldDrive.java]: are you sure they want this in pounds?

Comment (minhd-vu) [reply src/main/java/frc/robot/commands/drivebase/AbsoluteFieldDrive.java]: I think they want in kg

File: src/main/java/frc/robot/Constants.java [hunk 5]
```diff
@@ -31,11 +39,11 @@ public static final class AutoConstants {
 
   public static final class DrivebaseConstants {
     // Hold time on motor brakes when disabled.
-    public static final double WHEEL_LOCK_TIME = 10; // seconds
+    public static final Measure<Time> WHEEL_LOCK_TIME_SECS = Seconds.of(10); // seconds
```
Comment (minhd-vu) [inline src/main/java/frc/robot/Constants.java]:
```suggestion
    public static final Measure<Time> WHEEL_LOCK_TIME = Seconds.of(10);
```

**Review by minhd-vu — APPROVED** [review]
🔥
